### ISSUE TITLE
Embedding Service Binding Request

### ISSUE THREAD

**Issue by navidsh** [application-stacks/runtime-component-operator#100]
Add support for embedding Service Binding Request as a blob to `.spec.bindings.embedded` in the `RuntimeComponent` CRD e.g.

```yaml
spec:
  bindings:
    autoDetect: true
    resourceRef: my-binding
    embedded:
      apiVersion: apps.openshift.io/v1alpha1
      kind: ServiceBindingRequest
      spec:
        backingServiceSelectors:
          - group: kafka.strimzi.io
            kind: KafkaUser
            resourceRef: my-producer
            version: v1beta1
          - group: kafka.strimzi.io
            kind: Kafka
            resourceRef: my-cluster
            version: v1beta1
        customEnvVar:
          - name: BOOTSTRAP_SERVERS
            value: |-
              {{- range .status.listeners -}}
                {{- if and (eq .type "tls") (gt (len .addresses) 0) -}}
                  {{- with (index .addresses 0) -}}
                    {{ .host }}:{{ .port }}
                  {{- end -}}
                {{- end -}}
              {{- end -}}
```

Runtime Component Operator should fill up any of the following fields if not provided under `.spec.bindings.embedded`:
- `apiVersion`: defaults to `apps.openshift.io/v1alpha1`
- `kind`: defaults to `ServiceBindingRequest
- `metadata`: cannot be defined
