### ISSUE TITLE
Enhance Certificate Manager e2e test

### ISSUE THREAD

**Issue by edavidj** [application-stacks/runtime-component-operator#114]
Current tests cover:
- Creation of component using pod certificate (self-signed)
- Creation of component using route certificate (self-signed)

Add the following scenarios to the cert-manager tests

- [x] Override Issuer to be used (see 'Advanced Scenario')
- [x] Use existing certificates (see 'Advanced Scenario')
- [x] Toggle simple scenarios on/off and verify behaviour as expected

**Comment by arturdzm** [comment]
The other scenario would be good to test, It also would cover external secret, is to use OpenShift CA for pods certificates. 

Here is example of usage, the service annotation is causing certificate to be generated:

```
spec:
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: myapp-service-tls
    certificateSecretRef: myapp-service-tls
    port: 9443
  route:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  expose: true
```
The route then can be used without custom certificate (assuming wildcard *.apps.cluster-domain)

It would be good to also connect to route and service and validate that common name (DNS) on certificates matching expected as well that the pod can actually be reached
