### ISSUE TITLE
Avoid setting nodePort value on headless service

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#168]
### What did you do?

(Reported by Graham Charters)

When storage is configured with NodePort, it results in this error and reconciliation stops. Headless service, Deployment, etc are not created

`"message": "Service \"stateful-app-headless\" is invalid: spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'",`

Sample CR:

```
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: stateful-app
  namespace: default
spec:
  applicationImage: openliberty/samples:springPetClinic
  replicas: 1
  service:
    type: NodePort
    nodePort: 31002
    port: 9080
  storage:
    size: 1Gi
    mountPath: "/logs"
```

### What did you expect to see?

Service (headless) being created along with Deployment. 

### What did you see instead?

Error message (above)
