### ISSUE TITLE
PVC not getting created through volumeClaimTemplate

### ISSUE THREAD

**Issue by halim-lee** [application-stacks/runtime-component-operator#205]
### What did you do?

When I try to create persistent volume for a statefulset through volumeClaimTemplate, PVC does not get created.

### What did you expect to see?

PVC should be created with declared fields in volumeClaimTemplate.

### What did you see instead?

```
spec:
  storage:
    volumeClaimTemplate:
      metadata: {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Mi
        storageClassName: local-storage
      status: {} 
```
metadata and status fields are empty - which looks like the cause of PVC not getting created.

### Environment

OpenShift 4.7.13, Kubernetes 1.20
