### ISSUE TITLE
UpdateStrategy not getting cleared

### ISSUE THREAD

**Issue by halim-lee** [application-stacks/runtime-component-operator#208]
### What did you do?
When I set the update strategy to "OnDelete" for statefulSet or "Recreate" for deployment, then set them to null, the update strategy remains as OnDelete or Recreate.

```
  statefulSet:
    updateStrategy:
      type: OnDelete
    storage:
      size: 1Gi
      mountPath: "/logs"
```

```
  statefulSet:
    updateStrategy:
    storage:
      size: 1Gi
      mountPath: "/logs"
```

### What did you expect to see?

When update strategy field is null, it should set back to RollingUpdate.
