### ISSUE TITLE
Reset host in Route resource

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#299]
Configure host for Route:

```yaml
spec:
  expose: true
  route:
    host: mycompany-host
```

Created Route resource will get the host values

Then remove the route field
```yaml
spec:
  expose: true
```

The Route resource still has the host value.

- RCO
   - [x] Fixed
   - [x] Added tests
- OLO
   - [x] Fixed
   - [x] Added tests
- WLO
   - [x] Fixed
   - [x] Added tests
