### ISSUE TITLE
Operator can't handle 3 slashes in applicatioImage

### ISSUE THREAD

**Issue by Elyytscha** [application-stacks/runtime-component-operator#325]
### What did you do?

```
apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: example-git-repo
  namespace: example-git-project
spec:
  applicationImage: 'docker.example.com/example-company/example-git-project/example-git-repo:latest'
  applicationName: my-app
  env:
    ..
  expose: true
  pullPolicy: IfNotPresent
  resources: {}
  service:
    port: 9080
    type: ClusterIP
```

### What did you expect to see?

```
apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: example-git-repo
  namespace: example-git-project
spec:
  applicationImage: 'docker.example.com/example-company/example-git-project/example-git-repo:latest'
  applicationName: my-app
  env:
    ..
  expose: true
  pullPolicy: IfNotPresent
  resources: {}
  service:
    port: 9080
    type: ClusterIP
status:
  conditions:
    - lastTransitionTime: '2022-01-17T12:10:52Z'
      status: 'True'
      type: Reconciled
  imageReference: 'docker.example.com/example-company/example-git-project/example-git-repo:latest'
```

### What did you see instead?

```
apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: example-git-repo
  namespace: example-git-project
spec:
  applicationImage: 'docker.example.com/example-company/example-git-project/example-git-repo:latest'
  applicationName: my-app
  env:
    ..
  expose: true
  pullPolicy: IfNotPresent
  resources: {}
  service:
    port: 9080
    type: ClusterIP
status:
  conditions:
    - lastTransitionTime: '2022-01-17T12:14:13Z'
      message: 'invalid resource name "example-git-project/example-git-repo:latest": [may not contain ''/'']'
      status: 'False'
      type: Reconciled
  imageReference: 'docker.example.com/example-company/example-git-project/example-git-repo:latest'
```
operator logs:

```
2022-01-17T11:55:30.416Z	INFO	controllers.RuntimeComponent	Reconciling RuntimeComponent	{"Request.Namespace": "example-git-project-env", "Request.Name": "example-git-repo"}
2022-01-17T11:55:31.417Z	INFO	controllers.RuntimeComponent	Failed to find runtime-component-operator config map	{"Request.Namespace": "example-git-project-env", "Request.Name": "example-git-repo"}
2022-01-17T11:55:31.418Z	INFO	controllers.RuntimeComponent	Failed to update runtime-component-operator config map	{"Request.Namespace": "example-git-project-env", "Request.Name": "example-git-repo"}
2022-01-17T11:55:31.451Z	ERROR	utils	ManageError	{"ba.Namespace": "example-git-project-env", "ba.Name": "example-git-repo", "Condition": "Reconciled", "ba": {"apiVersion": "rc.app.stacks/v1beta2", "kind": "RuntimeComponent", "namespace": "example-git-project-env", "name": "example-git-repo"}, "error": "invalid resource name \"example-git-project/example-git-repo:latest\": [may not contain '/']"}
github.com/go-logr/zapr.(*zapLogger).Error
	/workspace/vendor/github.com/go-logr/zapr/zapr.go:132
github.com/application-stacks/runtime-component-operator/utils.(*ReconcilerBase).ManageError
	/workspace/utils/reconciler.go:177
github.com/application-stacks/runtime-component-operator/controllers.(*RuntimeComponentReconciler).Reconcile
	/workspace/controllers/runtimecomponent_controller.go:187
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:263
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1
	/workspace/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:198
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185
k8s.io/apimachinery/pkg/util/wait.UntilWithContext
	/workspace/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99
2022-01-17T11:55:31.451Z	DEBUG	controller-runtime.manager.events	Warning	{"object": {"kind":"RuntimeComponent","namespace":"example-git-project-env","name":"example-git-repo","uid":"420c30a9-409d-4cb1-8911-9e920c0d0df1","apiVersion":"rc.app.stacks/v1beta2","resourceVersion":"458222304"}, "reason": "ProcessingError", "message": "invalid resource name \"example-git-project/example-git-repo:latest\": [may not contain '/']"}
```

### Environment

rco operator: 0.8.0
ocp: 4.8.24

### Possible solution

support 3 slashes in application image ref

### Additional context

operator can't handle 3 slashes in application image ref

possible workaround: use image stream which points to images containing 3 slashes

for better understanding:
example-company -> multiple example-git-projects
example-git-project -> multiple example-git-repos
