### ISSUE TITLE
TargetPort under spec.service.ports is set to 0 when not defined

### ISSUE THREAD

**Issue by halim-lee** [application-stacks/runtime-component-operator#346]
### What did you do?

A clear and concise description of the steps you took (or insert a code snippet).

Defined `spec.service.ports.port` and left `spec.service.ports.targetPort` blank. After reconciliation, targetPort appears to be 0 in RuntimeComponent CR. 
```
spec:
  applicationImage: 'openliberty/samples:springPetClinic'
  applicationName: test-app
  pullPolicy: IfNotPresent
  replicas: 4
  resources: {}
  service:
    port: 9080
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 0
    type: ClusterIP
```

Service actually does assign the correct value to targetPort (same value as port).
```
spec:
  ports:
    - name: 9080-tcp
      protocol: TCP
      port: 9080
      targetPort: 9080
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
```

Looks like targetPort in RuntimeComponent CR does not get updated properly.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `RuntimeComponent` CR.

```
spec:
  applicationImage: 'openliberty/samples:springPetClinic'
  applicationName: test-app
  pullPolicy: IfNotPresent
  replicas: 4
  resources: {}
  service:
    port: 9080
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    type: ClusterIP
```
