### ISSUE TITLE
Notify user when using NodePort service type with nodePort value 0

### ISSUE THREAD

**Issue by halim-lee** [application-stacks/runtime-component-operator#347]
### What did you do?

Define service type as NodePort and set nodePort value to 0.

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `RuntimeComponent` CR.

Error message saying nodePort value cannot be set to 0 when using NodePort type.

### What did you see instead?

A clear and concise description of what you expected to happen (or insert a code snippet).
```
spec:
  applicationImage: 'openliberty/samples:springPetClinic'
  applicationName: test-app
  pullPolicy: IfNotPresent
  replicas: 4
  service:
    nodePort: 0
    port: 9080
    type: NodePort
```

The service's nodePort is actually assigned to a value in range 30000-32767. RuntimeComponent CR does not get updated with the newly assigned value.

### Possible solution
Error message notifying the user:
```
Service "test-app" is invalid: spec.ports[0].nodePort: Invalid value: 0:
        provided port is not in the valid range. The range of valid ports is
        30000-32767. nodePort value is assigned to N.
```

Or let user know that is was invalid and have them pick another nodePort number without reassigning the value.
