### ISSUE TITLE
Add affinity rules by default to schedule pods on different nodes across different zones

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#354]
By default, we should add perferred podAntiAffinity rules to spread the pods across different nodes and zones. This would help with high availability out of the box. Users can override with the `.spec.affinity.*` fields.

**Comment by leochr** [comment]
Affinity to add to Pod spec:
```yaml
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: app-name
            topologyKey: kubernetes.io/hostname
          weight: 50
```

Sample go method to create affinity with a set of labels

```go
func getAffinity(labels map[string]string) *corev1.Affinity {
	return &corev1.Affinity{
		PodAntiAffinity: &corev1.PodAntiAffinity{
			PreferredDuringSchedulingIgnoredDuringExecution: []corev1.WeightedPodAffinityTerm{
				{
					Weight: 50,
					PodAffinityTerm: corev1.PodAffinityTerm{
						TopologyKey: "kubernetes.io/hostname",
						LabelSelector: &metav1.LabelSelector{
							MatchLabels: labels,
						},
					},
				},
			},
		},
	}
}
```
