### ISSUE TITLE
Add support for prometheus based autoscaling

### ISSUE THREAD

**Issue by Elyytscha** [application-stacks/runtime-component-operator#365]
### Is your feature request related to a problem?

No

### Describe the solution you'd like
would be nice to support something like this:
```yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myapplication-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapplication-deployment
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Pods
    pods:
      metricName: myapplication_api_response_time_avg
      targetAverageValue: "500"
```

maybe like
```yaml
apiVersion: rc.app.stacks/v1beta2
kind: RuntimeComponent
metadata:
  name: my-app
spec:
  applicationImage: quay.io/my-repo/my-app:1.0
  service:
    type: ClusterIP
    port: 9080
  expose: true
  autoscaling:
    prometheus:
      - metricName: myapplication_api_response_time_avg
        metricAverageValue: 500
```
