### ISSUE TITLE
Support multiple routes (different paths)

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#449]
Operator supports only one route for a single path . Consider supporting multiple routes

Sample config:
```
spec:
  route:
    paths:
       - /api1
       - /api2
       - /api3
```
