### ISSUE TITLE
RCO has replica default to be zero for sample deployment

### ISSUE THREAD

**Issue by mtamboli** [application-stacks/runtime-component-operator#510]
### What did you do?

I am trying to create a default application for RCO and it gives `replicas: 0' and also expose for route is not enabled.

![image](https://user-images.githubusercontent.com/29490950/233137028-c2a7dbfe-cdc2-4f54-8a8e-248c3569d278.png)

A clear and concise description of the steps you took (or insert a code snippet).

### What did you expect to see?

A clear and concise description of what you expected to happen (or insert a code snippet). If possible, add `RuntimeComponent` CR.

I expected to see values similar to open liberty

![image](https://user-images.githubusercontent.com/29490950/233137368-6c667b4d-79b3-47f6-8f55-6d7f55009ddb.png)

### Environment

Describe the environment (e.g OpenShift/Kubernetes version information).

### Possible solution

Update default for RCO to match OLO/WLO.

**Comment by leochr** [comment]
@mtamboli This can be validated using this RCO driver:

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: rco-v1-catalog
  namespace: openshift-marketplace
spec:
  displayName: RCO 2023-04-13
  image: >-
    icr.io/appcafe/runtime-component-operator-catalog@sha256:baf6a37ea2ec9ae98217c3b555bb17effd0fb27c3445128b9f7b602e1247ec08
  sourceType: grpc
```

**Comment by mtamboli** [comment]
Installed new operator and verified. Sample application works fine by default.
```
kind: RuntimeComponent
apiVersion: rc.app.stacks/v1
metadata:
  name: runtimecomponent-sample
  namespace: rco-sample1
spec:
  applicationImage: >-
    icr.io/appcafe/open-liberty/samples/getting-started@sha256:9a6f6352bee814302fcf939dd640b7d3b3e02307330f82bc32b782e7a9feb8a3
  expose: true
  manageTLS: true
  replicas: 1
  service:
    port: 9443
```
