### ISSUE TITLE
Document pre-req for manageTLS: runtime must load certificates

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#538]
manageTLS mounts the certificates onto the runtime pods, but the runtime is responsible for loading the mounted certificates. Liberty containers load the certificates automatically into the default keystore / truststore at container startup. tWAS runtime doesn't have such equivalence. Document that the inorder for manageTLS to work end-to-end, runtime must load the certs.

**Comment by tam512** [comment]
The current workaround to install tWAS applications using RCO v1.2.0 is to use `spec.route.termination: edge` with `insecureEdgeTerminationPolicy: Redirect` or `insecureEdgeTerminationPolicy: Allow` or `spec.route.termination: edge.passthrough`

For example:
```
spec:
  route:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  service:
    type: ClusterIP
    port: 9080
```
