### ISSUE TITLE
Auto scaling is not working as expected

### ISSUE THREAD

**Issue by leochr** [application-stacks/runtime-component-operator#68]
Expected to see 2 pods with the following settings, but the second pod is created and then quickly deleted. Keeps repeating it.

CR:

```
  applicationImage: 'openliberty/open-liberty:full-java8-openj9-ubi'
  autoscaling:
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 75
  resourceConstraints:
    limits:
      cpu: '4'
      memory: 2Gi
    requests:
      cpu: 300m
      memory: 512Mi
```

We need to fix this for Open Liberty Operator and Appsody Operator as well.

Analysis:

Horizontal Pod Autoscaler(HPA) attempts to change `Deployment`. But since the operator continuously watches `Deployment`, the change by `HPA` are reversed.
