### ISSUE TITLE
Adding support for external service bindings

### ISSUE THREAD

**Issue by navidsh** [application-stacks/runtime-component-operator#69]
Tools like `odo` may adopt `ServiceBinding` CR as the resource it creates for service. In that case, users can create the binding themselves and our operator should be able to point to the Service Binding CRs created externally:

```yaml
spec:
  bindings:
    autoDetect: <true or false>
    resourceRef: <name of a manually created ServiceBinding CR>
```

More details on the PR: https://github.com/application-stacks/runtime-component-operator/pull/76
